/**
 * MyMind Clone - Pinecone Vector Database Integration
 *
 * Uses Pinecone with explicit embeddings generated by the app.
 * Provides semantic similarity search for "See Similar" functionality.
 *
 * @fileoverview Pinecone vector database utilities using official SDK
 */

import { Pinecone } from '@pinecone-database/pinecone'

import {
  embedDocument,
  embedQuery,
  getEmbeddingProvenance,
  isEmbeddingsConfigured,
} from 'src/lib/ai/embeddings'
import { hexToColorName } from 'src/lib/ai/tagVocabulary'

// =============================================================================
// CONFIGURATION
// =============================================================================

const PINECONE_API_KEY = process.env.PINECONE_API_KEY
const PINECONE_HOST = process.env.PINECONE_HOST

// Lazy-initialized client
let pineconeClient: Pinecone | null = null

/**
 * Check if Pinecone is configured.
 */
export function isPineconeConfigured(): boolean {
  return !!(PINECONE_API_KEY && PINECONE_HOST && isEmbeddingsConfigured())
}

/**
 * Get or create the Pinecone client.
 */
function getClient(): Pinecone | null {
  if (!isPineconeConfigured()) {
    return null
  }

  if (!pineconeClient) {
    pineconeClient = new Pinecone({
      apiKey: PINECONE_API_KEY!,
    })
  }

  return pineconeClient
}

/**
 * Get the index instance.
 */
function getIndex() {
  const client = getClient()
  if (!client || !PINECONE_HOST) {
    return null
  }

  return client.index('mymind-knowledge', PINECONE_HOST)
}

// =============================================================================
// PINECONE OPERATIONS
// =============================================================================

interface PineconeRecord {
  id: string
  text: string
  metadata?: Record<string, string | number | boolean | string[]>
}

interface PineconeMatch {
  id: string
  score: number
  metadata?: Record<string, unknown>
}

/**
 * Upserts a record to Pinecone using an explicit embedding vector.
 */
export async function upsertRecord(
  record: PineconeRecord
): Promise<boolean> {
  const index = getIndex()
  if (!index) {
    console.warn('[Pinecone] Not configured, skipping upsert')
    return false
  }

  try {
    const vector = await embedDocument(record.text)
    const provenance = getEmbeddingProvenance()
    await index.upsert([
      {
        id: record.id,
        values: vector,
        metadata: {
          ...(record.metadata || {}),
          embedding_provider: provenance.provider || '',
          embedding_model: provenance.model || '',
        },
      },
    ])

    console.log(`[Pinecone] Upserted record: ${record.id}`)
    return true
  } catch (error) {
    console.error('[Pinecone] Upsert error:', error)
    return false
  }
}

/**
 * Queries Pinecone for similar records using explicit embeddings.
 *
 * @param queryText - The text to find similar records for
 * @param topK - Number of results to return (default 5)
 * @param excludeId - Optional record ID to exclude from results
 */
export async function querySimilar(
  queryText: string,
  topK: number = 5,
  excludeId?: string
): Promise<PineconeMatch[]> {
  const index = getIndex()
  if (!index) {
    console.warn('[Pinecone] Not configured, returning empty results')
    return []
  }

  try {
    const vector = await embedQuery(queryText)
    const response = await index.query({
      vector,
      topK: excludeId ? topK + 1 : topK,
      includeMetadata: true,
    })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let matches: PineconeMatch[] = (response.matches || []).map(
      (hit: any) => ({
        id: hit.id,
        score: hit.score,
        metadata: hit.metadata as Record<string, unknown> | undefined,
      })
    )

    // Filter out the excluded ID (typically the current card)
    if (excludeId) {
      matches = matches.filter((m) => m.id !== excludeId).slice(0, topK)
    }

    console.log(`[Pinecone] Found ${matches.length} similar records`)
    return matches
  } catch (error) {
    console.error('[Pinecone] Query error:', error)
    return []
  }
}

/**
 * Deletes a record from Pinecone.
 */
export async function deleteRecord(id: string): Promise<boolean> {
  const index = getIndex()
  if (!index) {
    return false
  }

  try {
    await index.deleteOne(id)
    console.log(`[Pinecone] Deleted record: ${id}`)
    return true
  } catch (error) {
    console.error('[Pinecone] Delete error:', error)
    return false
  }
}

/**
 * Builds the text field for Pinecone from card data.
 * Combines title, summary, tags, and image analysis fields
 * for rich semantic representation that enables cross-modal discovery.
 */
export function buildEmbeddingText(card: {
  title?: string | null
  content?: string | null
  tags?: string[] | null
  metadata?: {
    summary?: string
    author?: string
    authorName?: string
    authorHandle?: string
    platform?: string
    objects?: string[]
    ocrText?: string | null
    visualElements?: string[]
    texture?: string
    composition?: string
    colors?: string[]
    paletteType?: string
  } | null
}): string {
  const parts: string[] = []

  if (card.title) {
    parts.push(card.title)
  }

  // Prefer summary over raw content (more semantic value)
  if (card.metadata?.summary) {
    parts.push(card.metadata.summary)
  } else if (card.content) {
    // Truncate raw content to avoid token limits
    parts.push(card.content.slice(0, 500))
  }

  const author =
    card.metadata?.authorName ||
    card.metadata?.authorHandle ||
    card.metadata?.author
  if (author) {
    parts.push(`Author: ${author}`)
  }

  if (card.metadata?.platform) {
    parts.push(`Platform: ${card.metadata.platform}`)
  }

  if (card.tags && card.tags.length > 0) {
    parts.push(`Tags: ${card.tags.join(', ')}`)
  }

  // Image analysis fields for cross-modal semantic search
  if (card.metadata?.objects && card.metadata.objects.length > 0) {
    parts.push(`Objects: ${card.metadata.objects.join(', ')}`)
  }

  if (card.metadata?.ocrText) {
    parts.push(`Text in image: ${card.metadata.ocrText.slice(0, 300)}`)
  }

  if (
    card.metadata?.visualElements &&
    card.metadata.visualElements.length > 0
  ) {
    parts.push(`Visual: ${card.metadata.visualElements.join(', ')}`)
  }

  if (card.metadata?.texture || card.metadata?.composition) {
    const styleParts = [card.metadata.texture, card.metadata.composition].filter(
      Boolean
    )
    parts.push(`Style: ${styleParts.join(', ')}`)
  }

  if (card.metadata?.colors && card.metadata.colors.length > 0) {
    const colorNames = card.metadata.colors.map(hexToColorName)
    parts.push(`Colors: ${colorNames.join(', ')}`)
  }

  if (card.metadata?.paletteType) {
    parts.push(`Palette: ${card.metadata.paletteType}`)
  }

  return parts.join('. ')
}
